services:
  - type: web
    name: sudharsan-server
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    rootDir: server

  - type: web
    name: sudharsan-client
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "serve -s build"
    plan: free
    rootDir: client
